### PR TITLE
aiohttp==3.5 compatibility added

### PR DESCRIPTION
**Pull request by Derfirm**

### CODE REVIEW

**Comment by vtm9** [comment]
Yo, when anybody merge it?

**Comment by vtm9** [comment]
@pnuckowski

**Comment by thanosexcite** [comment]
Thanks @Derfirm . I installed your branch to test it and and the error in #113 is resolved with it.

**Comment by vtm9** [comment]
Let's merge it and publish

**Comment by pnuckowski** [comment]
@Derfirm  thanks for PR 🎉

**Pull request merged**
