### PR TITLE
use ClientSession base_url and headers

### PR DESCRIPTION
**Pull request by rsaleev**
Solves https://github.com/pnuckowski/aioresponses/issues/230

### CODE REVIEW

**Comment by pnuckowski** [comment]
@rsaleev 
Hi there,

Thank you for your pull request. I appreciate the effort you've put in. However, I regret to inform you that I won't be able to merge this at the moment. There seem to be significant formatting changes, and I couldn't find any accompanying test cases for this alteration.

**Comment by RafaelWO** [comment]
Thanks for your contribution, @rsaleev! 

I am excited to see this be fixed/merged and thus I am happy to help clean up the formatting and add tests - if you are busy with other things :slightly_smiling_face:

**Comment by rsaleev** [comment]
> Thanks for your contribution, @rsaleev! 
> 
> I am excited to see this be fixed/merged and thus I am happy to help clean up the formatting and add tests - if you are busy with other things :slightly_smiling_face: 

Yes, please.

**Comment by RafaelWO** [comment]
I created a new PR containing only the actual fix (without reformatting code) here: #258 

I will add tests as well as soon as if have time :slightly_smiling_face:

**Pull request closed without merging**
